## ==========================
## Production Profile
## ==========================
#
#spring.jpa.show-sql=false
#
#spring.jpa.hibernate.ddl-auto=validate
#
#logging.level.root=WARN


spring.datasource.url=jdbc:postgresql://postgres:5432/account_db
spring.datasource.username=sneha.satish
spring.datasource.password=Valtech@2026

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

eureka.client.service-url.defaultZone=http://service-registry:8761/eureka

logging.level.root=WARN