# ==========================
# Development Profile
# ==========================

spring.jpa.show-sql=true

logging.level.root=DEBUG

logging.level.io.github.resilience4j.retry=DEBUG
logging.level.io.github.resilience4j.circuitbreaker=DEBUG